parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Elate\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,ElateKernel.php}'
